package main

import (
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

func TestClassifyShimContent(t *testing.T) {
	winDev := "@echo off\r\nrem devhub dev shim - runs this checkout from source via \"go run\" so edits\r\nrem take effect with no rebuild. Generated by scripts\\dev.ps1 install.\r\npushd D:\\program\\devhub\r\ngo run ./cmd/devhub %*\r\npopd\r\n"
	if k, d := classifyShimContent(winDev); k != shimSource || d != `D:\program\devhub` {
		t.Errorf("windows dev shim = (%v, %q)", k, d)
	}

	unixDev := "#!/usr/bin/env bash\n# devhub dev shim — runs this checkout from source via 'go run' so edits take\n# effect with no rebuild. Generated by scripts/dev.sh install.\ncd \"/home/u/devhub\" || exit 1\nexec go run ./cmd/devhub \"$@\"\n"
	if k, d := classifyShimContent(unixDev); k != shimSource || d != "/home/u/devhub" {
		t.Errorf("unix dev shim = (%v, %q)", k, d)
	}

	// Release shim written by the current install.ps1 (marker + exec line).
	winRelease := "@echo off\r\nrem devhub release shim - runs the pinned binary installed by install.ps1\r\n\"C:\\Users\\u\\AppData\\Local\\devhub\\bin\\devhub.exe\" %*\r\n"
	if k, d := classifyShimContent(winRelease); k != shimRelease || d != `C:\Users\u\AppData\Local\devhub\bin\devhub.exe` {
		t.Errorf("windows release shim = (%v, %q)", k, d)
	}

	// Legacy release shim (pre-marker): only the exec line identifies it.
	winReleaseOld := "@echo off\r\n\"C:\\Users\\u\\AppData\\Local\\devhub\\bin\\devhub.exe\" %*\r\n"
	if k, d := classifyShimContent(winReleaseOld); k != shimRelease || d == "" {
		t.Errorf("legacy release shim = (%v, %q)", k, d)
	}

	if k, _ := classifyShimContent("#!/bin/sh\nexec something-else\n"); k != shimUnknown {
		t.Errorf("foreign content should be unknown, got %v", k)
	}
}

func TestScanPathForDevhub(t *testing.T) {
	// Windows: PATHEXT order within a dir (exe beats cmd), dir order across
	// dirs, case-insensitive dedup of repeated PATH entries. Keys go through
	// filepath.Join so the separators match on any host OS running this test,
	// and the exists fake is case-insensitive like a real Windows filesystem.
	files := map[string]bool{}
	for _, p := range [][2]string{{`C:\bin`, "devhub.cmd"}, {`C:\bin`, "devhub.exe"}, {`C:\repo`, "devhub.cmd"}} {
		files[strings.ToLower(filepath.Join(p[0], p[1]))] = true
	}
	exists := func(p string) bool { return files[strings.ToLower(p)] }
	got := scanPathForDevhub([]string{`C:\bin`, `C:\missing`, `C:\repo`, `C:\BIN`, ""}, true, exists)
	want := []string{
		filepath.Join(`C:\bin`, "devhub.exe"),
		filepath.Join(`C:\bin`, "devhub.cmd"),
		filepath.Join(`C:\repo`, "devhub.cmd"),
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("windows scan = %v, want %v", got, want)
	}

	// Unix: plain name, no PATHEXT expansion. filepath.Join separators depend
	// on the host OS, so build the expectation with it.
	udir := "/usr/local/bin"
	utarget := filepath.Join(udir, "devhub")
	got = scanPathForDevhub([]string{udir}, false, func(p string) bool { return p == utarget })
	if len(got) != 1 || got[0] != utarget {
		t.Errorf("unix scan = %v, want [%s]", got, utarget)
	}
}
