<#
.SYNOPSIS
  devhub をソースから起動する開発用ヘルパ（Windows / PowerShell 版）。

.DESCRIPTION
  配布バイナリを使わず（= 会社規定でバイナリ不可な環境向け）、このスクリプトが
  属する worktree のコードを `go run` でそのまま起動する。アセットは module
  ルートからの go:embed なので、worktree ごとに「いま編集中のソース」が反映される。

.PARAMETER Action
  run（既定） | build | install | stop | restart | status

.EXAMPLE
  scripts\dev.ps1 run
  $env:DEVHUB_PORT=9000; scripts\dev.ps1 run    # 別ポートで検証インスタンス
  $env:DEVHUB_PORT=9000; scripts\dev.ps1 stop   # そのポートの devhub を停止
  scripts\dev.ps1 run -- --no-browser           # devhub 本体へ引数を透過
  scripts\dev.ps1 install                       # PATH 上の devhub を「ソースから go run するシム」にする

  環境変数: DEVHUB_PORT（既定 8765） / DEVHUB_HOME（既定 %LOCALAPPDATA%\devhub）
            install 先: DEVHUB_BIN_DIR（既定 %USERPROFILE%\bin）
#>
[CmdletBinding()]
param(
  [Parameter(Position = 0)]
  [ValidateSet('run', 'build', 'install', 'stop', 'restart', 'status')]
  [string]$Action = 'run',

  # run へ透過する追加引数（例: -- --no-browser）
  [Parameter(ValueFromRemainingArguments = $true)]
  [string[]]$Rest
)

$ErrorActionPreference = 'Stop'

# このスクリプトが属する worktree の repo ルートへ移動する。どこから呼んでも
# 「そのスクリプトのソース」を起動できるようにするため。
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location $RepoRoot

$Port = if ($env:DEVHUB_PORT) { [int]$env:DEVHUB_PORT } else { 8765 }
$env:DEVHUB_PORT = "$Port"

function Require-Cmd($name) {
  if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
    Write-Error "エラー: $name が見つかりません。"
  }
}

# DEVHUB_PORT を LISTEN している PID 群を返す。
function Get-Listeners {
  Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue |
    Select-Object -ExpandProperty OwningProcess -Unique
}

# 先頭の "--" 区切りを取り除く（run -- --no-browser のため）。
function PassThruArgs {
  if ($Rest -and $Rest.Count -gt 0 -and $Rest[0] -eq '--') {
    return $Rest[1..($Rest.Count - 1)]
  }
  return $Rest
}

switch ($Action) {
  'run' {
    Require-Cmd go
    $dataHome = if ($env:DEVHUB_HOME) { $env:DEVHUB_HOME } else { "$env:LOCALAPPDATA\devhub" }
    Write-Host "devhub をソースから起動します (port=$Port, home=$dataHome)"
    & go run ./cmd/devhub @(PassThruArgs)
  }
  'build' {
    Require-Cmd go
    & go build -o devhub.exe ./cmd/devhub
    Write-Host "ビルド完了: $RepoRoot\devhub.exe"
  }
  'install' {
    # 配布リリース(install.ps1)を待たず、いま手元のソースを `devhub` コマンドにする。
    # 固定 exe は作らず、PATH 上にこの worktree の `go run` を呼ぶ devhub.cmd シムを置く。
    # こうすると編集したソースが常にそのまま反映され、固定ビルドのような陳腐化
    # （古いコードが動き続ける）が起きない。配置先は DEVHUB_BIN_DIR に従う。
    Require-Cmd go
    $binDir = if ($env:DEVHUB_BIN_DIR) { $env:DEVHUB_BIN_DIR } else { "$env:USERPROFILE\bin" }
    New-Item -ItemType Directory -Force -Path $binDir | Out-Null
    $shim = Join-Path $binDir 'devhub.cmd'
    # cmd.exe は .cmd を OEM コードページで読むため、シム本体は ASCII のみで書く
    # （非 ASCII を混ぜると rem 行などのパースが壊れる）。RepoRoot を焼き込む。
    $content = @"
@echo off
rem devhub dev shim - runs this checkout from source via "go run" so edits
rem take effect with no rebuild. Generated by scripts\dev.ps1 install.
pushd $RepoRoot
go run ./cmd/devhub %*
popd
"@
    Set-Content -Path $shim -Value $content -Encoding ascii
    Write-Host "インストール完了: $shim (source: $RepoRoot, go run)"

    # DEVHUB_BIN_DIR が user PATH に無ければ追加（install.ps1 と同じ作法）。
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    $onPath = $false
    if ($userPath) {
      foreach ($item in ($userPath -split ';')) {
        if ($item.TrimEnd('\') -ieq $binDir.TrimEnd('\')) { $onPath = $true; break }
      }
    }
    if (-not $onPath) {
      $newUserPath = if ($userPath) { "$binDir;$userPath" } else { $binDir }
      [Environment]::SetEnvironmentVariable('Path', $newUserPath, 'User')
      $env:Path = "$binDir;$env:Path"
      Write-Host "PATH に追加しました（新しいターミナルから有効）: $binDir"
    }
    Write-Host "編集は次回 devhub 起動からそのまま反映されます（再ビルド不要）。"
    Write-Host "起動中インスタンスへ反映するには再起動してください: scripts\dev.ps1 stop → devhub"
  }
  'stop' {
    $pids = Get-Listeners
    if (-not $pids) {
      Write-Host "port $Port で LISTEN している devhub は見つかりません。"
      break
    }
    # ports ツールは安全のため devhub 自身を kill できないため、ここで停止する。
    Write-Host "port $Port のプロセスを停止します (pid: $($pids -join ', '))"
    foreach ($procId in $pids) { Stop-Process -Id $procId -Force }
  }
  'status' {
    $pids = Get-Listeners
    if (-not $pids) { Write-Host "port ${Port}: LISTEN なし" }
    else { Write-Host "port ${Port}: LISTEN 中 (pid: $($pids -join ', '))" }
  }
  'restart' {
    & $PSCommandPath stop
    Start-Sleep -Seconds 1 # ポート解放を待つ
    & go run ./cmd/devhub @(PassThruArgs)
  }
}
