<#
.SYNOPSIS
  devhub をソースから起動する開発用ヘルパ（Windows / PowerShell 版）。

.DESCRIPTION
  配布バイナリを使わず（= 会社規定でバイナリ不可な環境向け）、このスクリプトが
  属する worktree のコードを `go run` でそのまま起動する。アセットは module
  ルートからの go:embed なので、worktree ごとに「いま編集中のソース」が反映される。

.PARAMETER Action
  run（既定） | build | install | stop | restart | status

.EXAMPLE
  scripts\dev.ps1 run
  $env:DEVHUB_PORT=9000; scripts\dev.ps1 run    # 別ポートで検証インスタンス
  $env:DEVHUB_PORT=9000; scripts\dev.ps1 stop   # そのポートの devhub を停止
  scripts\dev.ps1 run -- --no-browser           # devhub 本体へ引数を透過
  scripts\dev.ps1 install                       # PATH 上の devhub を「ソースから go run するシム」にする

  環境変数: DEVHUB_PORT（保存済み設定を上書き） / DEVHUB_HOME（既定 %LOCALAPPDATA%\devhub）
            install 先: DEVHUB_BIN_DIR（既定 %USERPROFILE%\bin）
#>
[CmdletBinding()]
param(
  [Parameter(Position = 0)]
  [ValidateSet('run', 'build', 'install', 'stop', 'restart', 'status')]
  [string]$Action = 'run',

  # run へ透過する追加引数（例: -- --no-browser）
  [Parameter(ValueFromRemainingArguments = $true)]
  [string[]]$Rest
)

$ErrorActionPreference = 'Stop'

# このスクリプトが属する worktree の repo ルートへ移動する。どこから呼んでも
# 「そのスクリプトのソース」を起動できるようにするため。
$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
Set-Location $RepoRoot

$Port = if ($env:DEVHUB_PORT) { [int]$env:DEVHUB_PORT } else { $null }

function Require-Cmd($name) {
  if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
    Write-Error "エラー: $name が見つかりません。"
  }
}

# 先頭の "--" 区切りを取り除く（run -- --no-browser のため）。
function PassThruArgs {
  if ($Rest -and $Rest.Count -gt 0 -and $Rest[0] -eq '--') {
    return $Rest[1..($Rest.Count - 1)]
  }
  return $Rest
}

switch ($Action) {
  'run' {
    Require-Cmd go
    $dataHome = if ($env:DEVHUB_HOME) { $env:DEVHUB_HOME } else { "$env:LOCALAPPDATA\devhub" }
    $portLabel = if ($Port) { $Port } else { 'saved setting' }
    Write-Host "devhub をソースから起動します (port=$portLabel, home=$dataHome)"
    & go run ./cmd/devhub start @(PassThruArgs)
  }
  'build' {
    Require-Cmd go
    & go build -o devhub.exe ./cmd/devhub
    Write-Host "ビルド完了: $RepoRoot\devhub.exe"
  }
  'install' {
    # 配布リリース(install.ps1)を待たず、いま手元のソースを `devhub` コマンドにする。
    # 固定 exe は作らず、PATH 上にこの worktree の `go run` を呼ぶ devhub.cmd シムを置く。
    # こうすると編集したソースが常にそのまま反映され、固定ビルドのような陳腐化
    # （古いコードが動き続ける）が起きない。配置先は DEVHUB_BIN_DIR に従う。
    Require-Cmd go
    $binDir = if ($env:DEVHUB_BIN_DIR) { $env:DEVHUB_BIN_DIR } else { "$env:USERPROFILE\bin" }
    New-Item -ItemType Directory -Force -Path $binDir | Out-Null
    $shim = Join-Path $binDir 'devhub.cmd'
    # コマンドスロットは 1 つ（install.ps1 のリリース版 shim と同じパス）。最後に
    # install した方が勝つ設計だが、置き換えは黙って行わず必ず告知する。
    if (Test-Path $shim) {
      $old = Get-Content $shim -Raw -ErrorAction SilentlyContinue
      if ($old -and $old -notmatch 'devhub dev shim') {
        Write-Host "[Notice] 既存のリリース版 shim を dev shim（ソース実行: $RepoRoot）に置き換えます。"
        Write-Host "         リリース版に戻すには: install.ps1 を再実行してください。"
      } elseif ($old -match '(?m)^pushd (.+?)\r?$' -and $Matches[1] -ne $RepoRoot) {
        Write-Host "[Notice] dev shim の参照先を切り替えます: $($Matches[1]) -> $RepoRoot"
      }
    }
    # cmd.exe は .cmd を OEM コードページで読むため、シム本体は ASCII のみで書く
    # （非 ASCII を混ぜると rem 行などのパースが壊れる）。RepoRoot を焼き込む。
    # Quoting protects cmd metacharacters such as spaces and '&'. Percent signs
    # still expand inside quotes, so double them before embedding the path.
    $cmdRepoRoot = $RepoRoot.Replace('%', '%%')
    $rootB64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($RepoRoot))
    $content = @"
@echo off
setlocal DisableDelayedExpansion
rem devhub dev shim - runs this checkout from source via "go run" so edits
rem take effect with no rebuild. Generated by scripts\dev.ps1 install.
rem devhub-source-root-b64: $rootB64
pushd "$cmdRepoRoot" || exit /b 1
go run ./cmd/devhub %*
set "_devhub_exit=%ERRORLEVEL%"
popd
exit /b %_devhub_exit%
"@
    Set-Content -Path $shim -Value $content -Encoding ascii
    Write-Host "インストール完了: $shim (source: $RepoRoot, go run)"

    # DEVHUB_BIN_DIR が user PATH に無ければ追加（install.ps1 と同じ作法）。
    $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
    $onPath = $false
    if ($userPath) {
      foreach ($item in ($userPath -split ';')) {
        if ($item.TrimEnd('\') -ieq $binDir.TrimEnd('\')) { $onPath = $true; break }
      }
    }
    if (-not $onPath) {
      $newUserPath = if ($userPath) { "$binDir;$userPath" } else { $binDir }
      [Environment]::SetEnvironmentVariable('Path', $newUserPath, 'User')
      $env:Path = "$binDir;$env:Path"
      Write-Host "PATH に追加しました（新しいターミナルから有効）: $binDir"
    }
    Write-Host "編集は次回 devhub 起動からそのまま反映されます（再ビルド不要）。"
    Write-Host "起動中インスタンスへ反映するには再起動してください: scripts\dev.ps1 stop → devhub"
  }
  'stop' {
    Require-Cmd go
    # The CLI probes /ai-api/info before signalling and refuses an unrelated
    # listener. Keep that identity check in one implementation on every OS.
    & go run ./cmd/devhub stop
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
  }
  'status' {
    Require-Cmd go
    & go run ./cmd/devhub status
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
  }
  'restart' {
    & $PSCommandPath stop
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    Start-Sleep -Seconds 1 # ポート解放を待つ
    & go run ./cmd/devhub start @(PassThruArgs)
  }
}
