#!/usr/bin/env bash
# devhub をソースから起動する開発用ヘルパ。
#
# 配布バイナリを使わず（= 会社規定でバイナリ不可な環境向け）、このスクリプトが
# 属する worktree のコードを `go run` でそのまま起動する。アセットは
# module ルートからの go:embed なので、worktree ごとに「いま編集中のソース」が
# そのまま反映される（固定ビルドの devhub コマンドのように repo に固定されない）。
#
# 使い方:
#   scripts/dev.sh [run|build|stop|restart|status]
#   scripts/dev.sh run -- <devhub への追加引数...>
#
# 例:
#   scripts/dev.sh run                     # 保存済み設定（初期値 8765）で起動
#   DEVHUB_PORT=9000 scripts/dev.sh run    # 別ポートで検証インスタンスを起動
#   DEVHUB_PORT=9000 scripts/dev.sh stop   # そのポートの devhub を停止
#   scripts/dev.sh run -- --no-browser     # devhub 本体へ引数を透過
#
# 環境変数:
#   DEVHUB_PORT  保存済み設定を上書きするリッスンポート
#   DEVHUB_HOME  データ/設定の格納先（既定 ~/.devhub。検証を本番と完全分離したいとき指定）
set -euo pipefail

# このスクリプトが属する worktree の repo ルートへ移動する。どこから呼んでも
# 「そのスクリプトのソース」を起動できるようにするため。
REPO_ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$REPO_ROOT"

PORT="${DEVHUB_PORT:-}"

require() { command -v "$1" >/dev/null 2>&1 || { echo "エラー: $1 が見つかりません。" >&2; exit 1; }; }

usage() {
  cat >&2 <<'EOF'
使い方: scripts/dev.sh [run|build|stop|restart|status]

  run       ソースから起動（既定）。`run -- <引数>` で devhub 本体へ透過
  build     ./devhub にバイナリをビルド
  install   PATH 上の `devhub` を「ソースから go run するシム」にする（再ビルド不要）
  stop      設定ポート（DEVHUB_PORT 指定時はその値）の devhub を停止
  restart   stop してから run
  status    設定ポート（DEVHUB_PORT 指定時はその値）の状況を表示

環境変数: DEVHUB_PORT（保存済み設定を上書き） / DEVHUB_HOME（既定 ~/.devhub）
          install 先: DEVHUB_BIN_DIR（既定 ~/.local/bin）
EOF
}

cmd_run() {
  require go
  echo "devhub をソースから起動します (port=${PORT:-saved setting}, home=${DEVHUB_HOME:-$HOME/.devhub})" >&2
  exec go run ./cmd/devhub start "$@"
}

cmd_build() {
  require go
  go build -o devhub ./cmd/devhub
  echo "ビルド完了: $REPO_ROOT/devhub" >&2
}

# 配布リリース(install.sh)を待たず、いま手元のソースを `devhub` コマンドにする。
# 固定バイナリは作らず、PATH 上にこの worktree の `go run` を呼ぶ薄いラッパを置く。
# こうすると編集したソースが常にそのまま反映され、固定ビルドのような陳腐化（古い
# コードが動き続ける）が起きない。配置先は install.sh と同じ DEVHUB_BIN_DIR に従う。
cmd_install() {
  require go
  require base64
  require tr
  local bindir dest quoted_root root_b64
  bindir="${DEVHUB_BIN_DIR:-$HOME/.local/bin}"
  dest="$bindir/devhub"
  mkdir -p "$bindir"
  # コマンドスロットは 1 つ（install.sh のリリース版リンクと同じパス）。最後に
  # install した方が勝つ設計だが、置き換えは黙って行わず必ず告知する。
  if [ -L "$dest" ]; then
    echo "[Notice] 既存のリリース版リンク（$(readlink "$dest")）を dev shim（ソース実行: ${REPO_ROOT}）に置き換えます。" >&2
    echo "         リリース版に戻すには: install.sh を再実行してください。" >&2
  elif [ -f "$dest" ]; then
    # Current shims carry an encoding-safe source-root marker. Decode it first;
    # retain the old cd "..." parser for shims written by earlier versions.
    root_marker=$(sed -n 's/^# devhub-source-root-b64: \([A-Za-z0-9+\/=]*\)$/\1/p' "$dest" | head -n1)
    old_root=""
    if [ -n "$root_marker" ]; then
      old_root=$(printf '%s' "$root_marker" | base64 --decode 2>/dev/null) || \
        old_root=$(printf '%s' "$root_marker" | base64 -D 2>/dev/null) || old_root=""
    fi
    if [ -z "$old_root" ]; then
      old_root=$(sed -n 's/^cd "\([^"]*\)".*/\1/p' "$dest" | head -n1)
    fi
    if [ -n "$old_root" ] && [ "$old_root" != "$REPO_ROOT" ]; then
      echo "[Notice] dev shim の参照先を切り替えます: $old_root → $REPO_ROOT" >&2
    fi
  fi
  # tmp は EXIT trap（グローバルスコープで実行される）から参照するため、あえて
  # local にしない。local だと set -u 下で trap 実行時に unbound variable になり
  # 掃除されない。書き込み失敗・中断時に中途半端なシムを残さないよう一旦 temp に
  # 書いてアトミックに差し替える（mv 成功後は $tmp が無くなり EXIT の rm は no-op）。
  tmp=$(mktemp "$bindir/.devhub.XXXXXX")
  trap 'rm -f "$tmp"' EXIT
  printf -v quoted_root '%q' "$REPO_ROOT"
  root_b64=$(printf '%s' "$REPO_ROOT" | base64 | tr -d '\r\n')
  cat >"$tmp" <<EOF
#!/usr/bin/env bash
# devhub dev shim — runs this checkout from source via 'go run' so edits take
# effect with no rebuild. Generated by scripts/dev.sh install.
# devhub-source-root-b64: $root_b64
cd -- $quoted_root || exit 1
exec go run ./cmd/devhub "\$@"
EOF
  chmod +x "$tmp"
  mv -f "$tmp" "$dest"          # アトミック差し替え
  echo "インストール完了: $dest (source: $REPO_ROOT, go run)" >&2
  echo "編集は次回 devhub 起動からそのまま反映されます（再ビルド不要）。" >&2
  echo "起動中インスタンスへ反映するには再起動してください: scripts/dev.sh stop → devhub" >&2
}

cmd_stop() {
  require go
  # The CLI verifies /ai-api/probe before signalling and refuses an unrelated
  # listener. Keep that identity check in one implementation on every OS.
  go run ./cmd/devhub stop
}

cmd_status() {
  require go
  go run ./cmd/devhub status
}

cmd_restart() {
  cmd_stop
  sleep 1 # ポート解放を待つ
  cmd_run "$@"
}

action="${1:-run}"
if [ "$#" -gt 0 ]; then shift; fi
if [ "${1:-}" = "--" ]; then shift; fi

case "$action" in
  run)            cmd_run "$@" ;;
  build)          cmd_build ;;
  install)        cmd_install ;;
  stop)           cmd_stop ;;
  restart)        cmd_restart "$@" ;;
  status)         cmd_status ;;
  -h|--help|help) usage ;;
  *)
    echo "不明なサブコマンド: $action" >&2
    usage
    exit 1
    ;;
esac
